<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ID' => 'ID',
    'Type' => 'Тип',
    'Section' => 'Раздел',
    'Key' => 'Ключ',
    'Value' => 'Значение',
    'Status' => 'Статус',
    'Description' => 'Описание',
    'Created Date' => 'Дата Создания',
    'Updated Date' => 'Дата Обновления',
    'Settings' => 'Настройки',
    'Create Setting' => 'Создать Настройку',
    'Select Type' => 'Выберите Тип',
    'Select Section' => 'Выберите Раздел',
    'Select Status' => 'Выберите Статус',
    'Actions' => 'Действия',
    'Active' => 'Включён',
    'Inactive' => 'Выключен',
    'Update Setting: {0} -> {1}' => 'Редактирование настройки: {0} -> {1}',
    'Update Setting' => 'Редактирование настройки',
    'Update' => 'Обновить',
    'Create' => 'Создать',
    'Delete' => 'Удалить',
    'Go Back' => 'Вернуться',
    'String' => 'Строка',
    'Integer' => 'Целое число',
    'Boolean' => '0 или 1',
    'Float' => 'Число с плавающей точкой',
    'Null' => 'Null',
    'Setting has been created.' => 'Настройка была сохранена.',
    'Setting has been updated.' => 'Настройка была обновлена.',
    'Setting has been deleted.' => 'Настройка была удалена.',
    'The requested page does not exist.' => 'Ошибка 404 - страница не найдена!',
];
