<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ID' => 'ID',
    'Type' => 'Tipo',
    'Section' => 'Sección',
    'Key' => 'Llave',
    'Value' => 'Valor',
    'Status' => 'Estado',
    'Description' => 'Descripción',
    'Created Date' => 'Fecha de creación',
    'Updated Date' => 'Fecha de actualización',
    'Settings' => 'Configuración',
    'Create Setting' => 'Crear configuración',
    'Select Type' => 'Seleccionar Tipo',
    'Select Section' => 'Seleccionar Sección',
    'Select Status' => 'Seleccionar Estado',
    'Actions' => 'Acciones',
    'Active' => 'Activo',
    'Inactive' => 'Inactivo',
    'Update Setting: {0} -> {1}' => 'Actualizar configuraciones: {0} -> {1}',
    'Update Setting' => 'Actualizar configuraciones',
    'Update' => 'Actualizar',
    'Create' => 'Crear',
    'Delete' => 'Eliminar',
    'Go Back' => 'Volver',
    'String' => 'Cadena de texto',
    'Integer' => 'Integral',
    'Boolean' => 'Booleano',
    'Float' => 'Número flotante',
    'Null' => 'Nulo',
    'Setting has been created.' => 'La configuración fue creada.',
    'Setting has been updated.' => 'La configuración fue actualizada.',
    'Setting has been deleted.' => 'La configuración fue eliminada.',
    'The requested page does not exist.' => 'La página que busca no existe.',
];
