<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ID' => 'ID',
    'Type' => '类型',
    'Section' => '节点',
    'Key' => '项',
    'Value' => '值',
    'Status' => '状态',
    'Description' => '描述',
    'Created Date' => '创建时间',
    'Updated Date' => '更新时间',
    'Settings' => '设置项',
    'Create Setting' => '新建设置项',
    'Select Type' => '选择类型',
    'Select Section' => '选择节点',
    'Select Status' => '选择状态',
    'Actions' => '操作',
    'Active' => '启用',
    'Inactive' => '禁用',
    'Update Setting: {0} -> {1}' => '更改设置: {0} -> {1}',
    'Update Setting' => '更改设置',
    'Update' => '更改',
    'Create' => '新建',
    'Delete' => '删除',
    'Go Back' => '返回',
    'String' => '字符型',
    'Integer' => '整型',
    'Boolean' => '布尔型',
    'Float' => '浮点型',
    'Null' => 'Null型',
    'Setting has been created.' => '设置项新建成功.',
    'Setting has been updated.' => '设置项更改成功.',
    'Setting has been deleted.' => '设置项删除成功',
    'The requested page does not exist.' => '请求的页面不存在.',
];
