<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ID' => 'ID',
    'Type' => '類型',
    'Section' => '節點',
    'Key' => '項',
    'Value' => '值',
    'Status' => '狀態',
    'Description' => '描述',
    'Created Date' => '創建時間',
    'Updated Date' => '更新時間',
    'Settings' => '設置項',
    'Create Setting' => '新建設置項',
    'Select Type' => '選擇類型',
    'Select Section' => '選擇節點',
    'Select Status' => '選擇狀態',
    'Actions' => '操作',
    'Active' => '啟用',
    'Inactive' => '禁用',
    'Update Setting: {0} -> {1}' => '更改設置: {0} -> {1}',
    'Update Setting' => '更改設置',
    'Update' => '更改',
    'Create' => '新建',
    'Delete' => '刪除',
    'Go Back' => '返回',
    'String' => '字元型',
    'Integer' => '整型',
    'Boolean' => '布爾型',
    'Float' => '浮點型',
    'Null' => 'Null型',
    'Setting has been created.' => '設置項新建成功.',
    'Setting has been updated.' => '設置項更改成功.',
    'Setting has been deleted.' => '設置項刪除成功',
    'The requested page does not exist.' => '請求的頁面不存在.',
];
