<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Actions' => 'Acties',
    'Create' => 'Aanmaken',
    'Create Setting' => 'Instelling aanmaken',
    'Created Date' => 'Aanmaak datum',
    'Description' => 'Omschrijving',
    'Go Back' => 'Ga terug',
    'ID' => 'ID',
    'Key' => 'Key',
    'Section' => 'Onderdeel',
    'Select Section' => 'Selecteer onderdeel',
    'Select Status' => 'Selecteer status',
    'Select Type' => 'Selecteer type',
    'Setting has been created.' => 'Instelling is aangemaakt',
    'Setting has been deleted.' => 'Instelling is verwijderd',
    'Setting has been updated.' => 'Instelling is bijgewerkt',
    'Settings' => 'Instellingen',
    'Status' => 'Status',
    'The requested page does not exist.' => 'De opgevraagde pagina bestaat niet',
    'Type' => 'Type',
    'Update' => 'Bijwerken',
    'Update Setting' => 'Instelling bijwerken',
    'Update Setting: {0} -> {1}' => 'Instelling bijwerken: {0} -> {1}',
    'Updated Date' => 'Bijgewerkt op',
    'Value' => 'Waarde',
];
