<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ID' => 'ID',
    'Type' => 'Typ',
    'Section' => 'Sektion',
    'Key' => 'Schlüssel',
    'Value' => 'Wert',
    'Status' => 'Status',
    'Description' => 'Beschreibung',
    'Created Date' => 'Erstellungsdatum',
    'Updated Date' => 'Änderungsdatum',
    'Settings' => 'Einstellungen',
    'Create Setting' => 'Einstellung hinzufügen',
    'Select Type' => 'Typ auswählen',
    'Select Section' => 'Sektion auswählen',
    'Select Status' => 'Status auswählen',
    'Actions' => 'Aktionen',
    'Active' => 'Aktiv',
    'Inactive' => 'Inaktiv',
    'Update Setting: {0} -> {1}' => 'Update Setting: {0} -> {1}',
    'Update Setting' => 'Einstellung ändern',
    'Update' => 'Ändern',
    'Create' => 'Hinzufügen',
    'Delete' => 'Löschen',
    'Go Back' => 'Gehe zurück',
    'String' => 'String',
    'Integer' => 'Integer',
    'Boolean' => 'Boolean',
    'Float' => 'Float',
    'Null' => 'Null',
    'Setting has been created.' => 'Einstellung wurde hinzugefügt.',
    'Setting has been updated.' => 'Einstellung wurde geändert.',
    'Setting has been deleted.' => 'Einstellung wurde gelöscht.',
    'The requested page does not exist.' => 'Die gewünschte Seite existiert nicht.',
];
