<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ID' => 'ID',
    'Type' => 'Type',
    'Section' => 'Section',
    'Key' => 'Key',
    'Value' => 'Value',
    'Status' => 'Status',
    'Description' => 'Description',
    'Created Date' => 'Created Date',
    'Updated Date' => 'Updated Date',
    'Settings' => 'Settings',
    'Create Setting' => 'Create Setting',
    'Select Type' => 'Select Type',
    'Select Section' => 'Select Section',
    'Select Status' => 'Select Status',
    'Actions' => 'Actions',
    'Active' => 'Active',
    'Inactive' => 'Inactive',
    'Update Setting: {0} -> {1}' => 'Update Setting: {0} -> {1}',
    'Update Setting' => 'Update Setting',
    'Update' => 'Update',
    'Create' => 'Create',
    'Delete' => 'Delete',
    'Go Back' => 'Go Back',
    'String' => 'String',
    'Integer' => 'Integer',
    'Boolean' => 'Boolean',
    'Float' => 'Float',
    'Null' => 'Null',
    'Setting has been created.' => 'Setting has been created.',
    'Setting has been updated.' => 'Setting has been updated.',
    'Setting has been deleted.' => 'Setting has been deleted.',
    'The requested page does not exist.' => 'The requested page does not exist.',
];
